#!/usr/bin/python
# -*- codding: utf-8 -*-
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from common.execute_command import write_one_parameter

# url : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/put-partner-events.html
if __name__ == '__main__':
    """

    """

    parameter_display_string = """
    # entries : The list of events to write to the event bus.
(structure)

The details about an event generated by an SaaS partner.
Time -> (timestamp)

The date and time of the event.

Source -> (string)

The event source that is generating the evntry.

Resources -> (list)

AWS resources, identified by Amazon Resource Name (ARN), which the event primarily concerns. Any number, including zero, may be present.
(string)

DetailType -> (string)

A free-form string used to decide what fields to expect in the event detail.

Detail -> (string)

A valid JSON string. There is no other schema imposed. The JSON string may contain fields and nested subobjects.
    """
    add_option_dict = {}

    #######################################################################
    # parameter display string
    add_option_dict["parameter_display_string"] = parameter_display_string
    # ex: add_option_dict["no_value_parameter_list"] = "--single-parameter"
    write_one_parameter("events", "put-partner-events", "entries", add_option_dict)





