#!/usr/bin/python
# -*- codding: utf-8 -*-
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from common.execute_command import write_one_parameter

# url : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/redshift-data/cancel-statement.html
if __name__ == '__main__':
    """
	describe-statement : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/redshift-data/describe-statement.html
	execute-statement : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/redshift-data/execute-statement.html
	list-statements : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/redshift-data/list-statements.html
    """

    parameter_display_string = """
    # id : The identifier of the SQL statement to cancel. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. This identifier is returned by ExecuteStatment and ListStatements .
    """
    add_option_dict = {}

    #######################################################################
    # parameter display string
    add_option_dict["parameter_display_string"] = parameter_display_string
    # ex: add_option_dict["no_value_parameter_list"] = "--single-parameter"
    write_one_parameter("redshift-data", "cancel-statement", "id", add_option_dict)





