#!/usr/bin/python
# -*- codding: utf-8 -*-
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from common.execute_command import write_two_parameter

# url : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/create-saml-provider.html
if __name__ == '__main__':
    """
	delete-saml-provider : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/delete-saml-provider.html
	get-saml-provider : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/get-saml-provider.html
	list-saml-providers : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-saml-providers.html
	update-saml-provider : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/update-saml-provider.html
    """

    parameter_display_string = """
    # saml-metadata-document : An XML document generated by an identity provider (IdP) that supports SAML 2.0. The document includes the issuerâs name, expiration information, and keys that can be used to validate the SAML authentication response (assertions) that are received from the IdP. You must generate the metadata document using the identity management software that is used as your organizationâs IdP.
For more information, see About SAML 2.0-based Federation in the IAM User Guide
    # name : The name of the provider to create.
This parameter allows (through its regex pattern ) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-
    """
    add_option_dict = {}
    add_option_dict["parameter_display_string"] = parameter_display_string
    # ex: add_option_dict["no_value_parameter_list"] = "--single-parameter"
    write_two_parameter("iam", "create-saml-provider", "saml-metadata-document", "name", add_option_dict)
