#!/usr/bin/python
# -*- codding: utf-8 -*-
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from common.execute_command import execute_one_parameter


# url : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/describe-type-registration.html
if __name__ == '__main__':
    """
	list-type-registrations : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/list-type-registrations.html
    """

    parameter_display_string = """
    # registration-token : The identifier for this registration request.
This registration token is generated by CloudFormation when you initiate a registration request using ``  RegisterType `` .
    """

    add_option_dict = {}
    #######################################################################
    # setting option use
    # ex: add_option_dict["setting_matching_parameter"] = "--owners"
    # ex: add_option_dict["setting_key"] = "owner_id"

    #######################################################################
    # single parameter
    # ex: add_option_dict["no_value_parameter_list"] = "--single-parameter"

    #######################################################################
    # parameter display string
    add_option_dict["parameter_display_string"] = parameter_display_string

    execute_one_parameter("cloudformation", "describe-type-registration", "registration-token", add_option_dict)